# Generated by Django 5.0.1 on 2024-01-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bulim_remove_category_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulimData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_image', models.ImageField(upload_to='post-image/')),
                ('post_hashtag', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bulim')),
            ],
        ),
    ]
